---

- name: Clean the netfilter table
  hosts: "{{ target | default('netfilter') }}"
  gather_facts: no
  roles:
    - role: "ClearTable"
      when: init|default(False)|bool

- name: Add rule to allow SSH access
  hosts: "{{ target | default('netfilter') }}"
  gather_facts: no
  roles:
    - role: "server"
      vars:
        added_port: "22"
      when: init|default(False)|bool

- name: Set DROP as default rule
  hosts: "{{ target | default('netfilter') }}"
  gather_facts: no
  roles:
    - role: "DropDefault"
      when: init|default(False)|bool

- name: Add new rule for specified port
  hosts: "{{ target | default('netfilter') }}"
  gather_facts: no
  roles:
    - role: "{{ mode | default('client') }}"
      vars:
        added_port: "{{ port }}"
        added_protocol: "{{ protocol | default('tcp') }}"
      when: port is defined