---
# tasks file for Client
- name: Add rule for OUTPUT chain
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED
    protocol: "{{ added_protocol | default('tcp') }}"
    source_port: "{{ added_port }}"
    jump: ACCEPT 

- name: Add rule for INPUT chain
  iptables:
    chain: INPUT
    ctstate: [NEW,ESTABLISHED]
    protocol: "{{ added_protocol | default('tcp') }}"
    destination_port: "{{ added_port }}"
    jump: ACCEPT
