---
# tasks file for Client
- name: Add rule for OUTPUT chain
  iptables:
    chain: OUTPUT
    ctstate: ESTABLISHED
    protocol: tcp
    source_port: "{{ added_port }}"
    jump: ACCEPT

- name: Add rule for INPUT chain
  iptables:
    chain: INPUT
    ctstate: [NEW,ESTABLISHED]
    protocol: tcp
    destination_port: "{{ added_port }}"
    jump: ACCEPT
